#builder
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#production
FROM alpine AS production
WORKDIR /dist
COPY --from=builder /app/dist .