server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3000;
    }

    location /content/ {
        alias /usr/share/nginx/content/;
        autoindex off;
    }
}
